---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: postgres
    spec:
      securityContext:
        runAsUser: 70
        fsGroup: 70
      containers:
      - name: postgres
        image: quay.io/ukhomeofficedigital/dq-postgres-docker
        securityContext:
          runAsNonRoot: true
